// auto-generated script registry
// this file is generated by tools/integrate.js
// do not edit manually

export const REGISTRY = [
  {
    "id": "custom-shortcuts-manager",
    "name": "Custom Shortcuts Manager",
    "description": "Full macro system with recording, common actions, custom JS, and per-site shortcuts",
    "version": "1.1.0",
    "enabled": true
  },
  {
    "id": "dark-mode-toggle",
    "name": "Dark Mode Toggle",
    "description": "Hybrid dark mode with smart CSS injection and filter fallback, per-site overrides",
    "version": "1.0.1",
    "enabled": true
  },
  {
    "id": "markdown-converter",
    "name": "Markdown Selector+Readability (with UI)",
    "description": "Select DOM, navigate with arrows, convert to Markdown (Turndown+GFM), Readability mode, floating toolbar + settings.",
    "version": "0.4.0",
    "enabled": true
  }
];
