// scan scripts/ directory and generate registry.js

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, '..');
const scriptsDir = join(rootDir, 'scripts');
const registryPath = join(rootDir, 'src', 'core', 'registry.js');

function scanScripts() {
  const registry = [];
  
  if (!statSync(scriptsDir).isDirectory()) {
    console.log('scripts/ directory not found, creating empty registry');
    writeRegistry(registry);
    return;
  }
  
  const files = readdirSync(scriptsDir).filter(f => f.endsWith('.user.js'));
  
  for (const file of files) {
    const filePath = join(scriptsDir, file);
    const content = readFileSync(filePath, 'utf-8');
    
    // try to extract QoL.registerScript() call
    const registerMatch = content.match(/QoL\.registerScript\s*\(\s*\{([^}]+(?:\{[^}]*\}[^}]*)*)\s*\}\s*\)/s);
    
    if (registerMatch) {
      const configStr = registerMatch[1];
      
      // extract basic fields (simple parsing)
      const idMatch = configStr.match(/id\s*:\s*['"]([^'"]+)['"]/);
      const nameMatch = configStr.match(/name\s*:\s*['"]([^'"]+)['"]/);
      const descMatch = configStr.match(/description\s*:\s*['"]([^'"]+)['"]/);
      const versionMatch = configStr.match(/version\s*:\s*['"]([^'"]+)['"]/);
      const enabledMatch = configStr.match(/enabled\s*:\s*(true|false)/);
      
      if (idMatch && nameMatch) {
        registry.push({
          id: idMatch[1],
          name: nameMatch[1],
          description: descMatch ? descMatch[1] : '',
          version: versionMatch ? versionMatch[1] : '1.0.0',
          enabled: enabledMatch ? enabledMatch[1] === 'true' : true
        });
      }
    } else {
      // try to extract from userscript headers as fallback
      const nameMatch = content.match(/@name\s+(.+)/);
      const descMatch = content.match(/@description\s+(.+)/);
      const versionMatch = content.match(/@version\s+(.+)/);
      
      if (nameMatch) {
        const id = file.replace('.user.js', '');
        registry.push({
          id,
          name: nameMatch[1].trim(),
          description: descMatch ? descMatch[1].trim() : '',
          version: versionMatch ? versionMatch[1].trim() : '1.0.0',
          enabled: true
        });
      }
    }
  }
  
  writeRegistry(registry);
  console.log(`Generated registry with ${registry.length} scripts`);
}

function writeRegistry(registry) {
  const content = `// auto-generated script registry
// this file is generated by tools/integrate.js
// do not edit manually

export const REGISTRY = ${JSON.stringify(registry, null, 2)};
`;
  
  writeFileSync(registryPath, content, 'utf-8');
}

scanScripts();

